item: "Minot_2013_gut_phage" # id for the SPIRE item
processing_level: "study" # "study" or "sample"
tradeoff: 0.8

# item: "SAMN07510030" # id for the SPIRE item
# processing_level: "sample" # "study" or "sample"
